# Generated by Django 4.1.5 on 2023-01-13 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Writer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("createdDate", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_title", models.TextField(blank=True, max_length=50, null=True)),
                ("text", models.CharField(blank=True, max_length=200, null=True)),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
                ("createdDate", models.DateTimeField(auto_now_add=True)),
                ("updatedDate", models.DateTimeField(auto_now=True)),
                (
                    "refWriter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.writer"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "The Questions",
            },
        ),
    ]
