# Generated by Django 4.1.5 on 2023-01-13 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={},
        ),
        migrations.RemoveField(
            model_name="article",
            name="pub_date",
        ),
        migrations.RemoveField(
            model_name="article",
            name="updatedDate",
        ),
    ]
